input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [type] == "docker" {
    json {
      source => "message"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "devops-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}